### ISSUE TITLE
申请更换友链地址

### ISSUE THREAD

**Issue by 3272737852** [bqxqn/bqxqn.github.io#1]
我的个人工具分享站地址已从3272737852.top更换为http://www.kinghub.top
旧域名已停止续费并弃用。
请求将友链地址更改为新域名。

**Comment by bqxqn** [comment]
emm.....等下啊我那个bqxqn的那个博客不用了，我可以在我的新博客smdzhm.github.io上帮你添加友链




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bqxqn/bqxqn.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月16日(星期六) 晚上7:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[bqxqn/bqxqn.github.io] 申请更换友链地址 (Issue #1)





 
我的个人工具分享站地址已从3272737852.top更换为http://www.kinghub.top
 旧域名已停止续费并弃用。
 请求将友链地址更改为新域名。

**Comment by 3272737852** [comment]
可以的，没问题。那我这边关于你的友链将在我下次更新进行修改

**Comment by bqxqn** [comment]
但是有一问题是，你的网站进不去，显示重定向次数过多


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bqxqn/bqxqn.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月16日(星期六) 晚上8:06
***@***.***&gt;;
抄送:&nbsp;"邉?  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [bqxqn/bqxqn.github.io] 申请更换友链地址 (Issue #1)





 
可以的，没问题。那我这边关于你的友链将在我下次更新进行修改

**Comment by 3272737852** [comment]
这边是可以正常访问的，可能由于挂了cloudflare导致的，可以多尝试几遍或使用魔法。
